### ISSUE TITLE
Cannot run example scripts. OOM Error

### ISSUE THREAD

**Issue by Exusial** [MooreThreads/Moore-AnimateAnyone#10]
Thank you for your great work. When I directly run your provided command, it gives "RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1024 and 768x320)"
![1705137120120](https://github.com/MooreThreads/Moore-AnimateAnyone/assets/51511617/dc9c21f9-d4ab-4234-94cf-75e947f3293f)

**Comment by lixunsong** [comment]
Can you paste a screenshot of error message? I'm not sure which step this error raises. 80GB VRAM is definetly enough.
