### ISSUE TITLE
How to run on a single pose image?

### ISSUE THREAD

**Issue by Exusial** [MooreThreads/Moore-AnimateAnyone#12]
I try to run the inference on a single input pose image, but it will cause uc_mask error and cannot run.
![1705140908728](https://github.com/MooreThreads/Moore-AnimateAnyone/assets/51511617/d6ed1d30-f72d-4cc9-8232-2558f91d2239)

**Comment by lixunsong** [comment]
Does single pose image mean just generate one image instead of a video?

**Comment by wandrzej** [comment]
just re-posing a character. and it's exactly what I was trying to do, although with 2 frame video and get the same error. 
I'm assuming  there's some minimum length of the video that is needed and that's why get an error
