### ISSUE TITLE
Questions about training dataset

### ISSUE THREAD

**Issue by huanngzh** [MooreThreads/Moore-AnimateAnyone#2]
Such an open source effort with amazing results!
I have some questions about training data. What is the approximate amount of video data used to train the model?

**Comment by lixunsong** [comment]
Hi @huanngzh, we now utilize about 10k videos to train the model

**Comment by syorami** [comment]
> Hi @huanngzh, we now utilize about 10k videos to train the model

It's claimed that animate anyone uses a train data of around 5k videos. Doubling that dataset size would boost the model performance?
