### ISSUE TITLE
colab demo

### ISSUE THREAD

**Issue by loboere** [MooreThreads/Moore-AnimateAnyone#20]
someone be so kind as to make a google colab to test this thanks :)

**Comment by G-force78** [comment]
You can use the command line in this one, need to change the paths in the YAML to your own.
https://colab.research.google.com/drive/1e_LpbLCcgHEuvKXiw9G2XNTho3xB6ceK#scrollTo=DJxzTyuKbIX1

**Comment by nihilisticneuralnet** [comment]
Thanks @G-force78

**Comment by nihilisticneuralnet** [comment]
The gradio demo is giving `Unexpected token '<', "<html> <h"... is not valid JSON` error
