### ISSUE TITLE
vid2pose.py: No module named 'src'

### ISSUE THREAD

**Issue by botnang** [MooreThreads/Moore-AnimateAnyone#22]
Traceback (most recent call last):
  File "E:\AI\Moore-AnimateAnyone\tools\vid2pose.py", line 1, in <module>
    from src.dwpose import DWposeDetector
ModuleNotFoundError: No module named 'src'

![image](https://github.com/MooreThreads/Moore-AnimateAnyone/assets/32015065/fcc8e1a7-b1e6-408c-82db-ecb517c5d2c4)

**Comment by lixunsong** [comment]
Just run the shell command `export PYTHONPATH=$(pwd)` under the root directory.

**Comment by botnang** [comment]
thanks for you help. I have solved it under Win11:

**Comment by zhangtao22** [comment]
thank you
