### ISSUE TITLE
 mat1 and mat2 shapes cannot be multiplied (2x1024 and 768x320)

### ISSUE THREAD

**Issue by zhaoyun0071** [MooreThreads/Moore-AnimateAnyone#24]
mat1 and mat2 shapes cannot be multiplied (2x1024 and 768x320)

**Comment by lixunsong** [comment]
Did you download the image_encoder weights and config file from this link: https://huggingface.co/lambdalabs/sd-image-variations-diffusers/tree/main/image_encoder ?

**Comment by zhaoyun0071** [comment]
> Did you download the image_encoder weights and config file from this link: https://huggingface.co/lambdalabs/sd-image-variations-diffusers/tree/main/image_encoder ?

many thanks
I pretended to be clever and used the ipadapter image_encoder
