### ISSUE TITLE
Is it right for these flicker result? 

### ISSUE THREAD

**Issue by VisionU** [MooreThreads/Moore-AnimateAnyone#32]
Very good job! I run you code in Colab，use anyone-video-2 kpts in your lib, just choose my reference img, but the results seem to no good, can you check it?

https://github.com/MooreThreads/Moore-AnimateAnyone/assets/9945763/8ffb63df-7b7a-4b68-ac9d-3d557fb8e15c

https://github.com/MooreThreads/Moore-AnimateAnyone/assets/9945763/923be2ef-be2b-46ba-a0bd-83295b0aca50

**Comment by lixunsong** [comment]
I think it's unusual, seems the motion module is not loaded.

**Comment by G-force78** [comment]
> I think it's unusual, seems the motion module is not loaded.

How do you check that it is loaded and why would it not load properly?

**Comment by lixunsong** [comment]
You may first check whether the demo examples work properly

**Comment by G-force78** [comment]
> You may first check whether the demo examples work properly

That is really vague and unhelpful. I have solved it now anyway.

**Comment by thigazholi** [comment]
Hey what is the motion module, and how did you fix it?

> > You may first check whether the demo examples work properly
> 
> That is really vague and unhelpful. I have solved it now anyway.

**Comment by G-force78** [comment]
> Hey what is the motion module, and how did you fix it?
> 
> > > You may first check whether the demo examples work properly
> > 
> > 
> > That is really vague and unhelpful. I have solved it now anyway.

Check your path is correct here in animation.yaml, 
motion_module_path: "./pretrained_weights/motion_module.pth"
and check in line 25 of app.py that you have the right path for animation.yaml

**Comment by thigazholi** [comment]
> > Hey what is the motion module, and how did you fix it?
> > > > You may first check whether the demo examples work properly
> > > 
> > > 
> > > That is really vague and unhelpful. I have solved it now anyway.
> 
> Check your path is correct here in animation.yaml, motion_module_path: "./pretrained_weights/motion_module.pth" and check in line 25 of app.py that you have the right path for animation.yaml

Yes, they were correctly mentioned. However, when I try with custom images or pose videos, there seems to be a lot of flickering.
