### ISSUE TITLE
3D Computation Clarity in unet_3d, resnet_3d, and transform_3d

### ISSUE THREAD

**Issue by chenxinhua** [MooreThreads/Moore-AnimateAnyone#33]
I have a question: unet_3d, resnet_3d, and transform_3d only deal with dimensional transformations, yet there is no indication anywhere that 3D computation is necessary.

**Comment by lixunsong** [comment]
In stage2, motion module will be inserted into the 3d unet. This will perform temporal self-attention, which differs from 2d unet. So we keep them seperately.
