### ISSUE TITLE
How can i create a motion sequence video based on a video recored by myself

### ISSUE THREAD

**Issue by toby1123yjh** [MooreThreads/Moore-AnimateAnyone#37]
As the title mentioned , I want to use other motion sequences to test the model

**Comment by lixunsong** [comment]
Please refer: https://github.com/MooreThreads/Moore-AnimateAnyone?tab=readme-ov-file#-inference. Run this command:
`python tools/vid2pose.py --video_path /path/to/your/video.mp4`

**Comment by kackbob** [comment]
Yes. You first get ks video,after that you can test your video
