### ISSUE TITLE
I get this error, but all files are fine and also the config.json 

### ISSUE THREAD

**Issue by gunjahman** [MooreThreads/Moore-AnimateAnyone#4]
We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ./pretrained_weights/sd-vae-ft-mse is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode

**Comment by lixunsong** [comment]
Hello @gunjahman , have you install complete files of sd-vae-ft-mse? The issue is likely caused by missing the file path, so I suggest you check the path and its configuration in the config file.

**Comment by gunjahman** [comment]
Thank you for your answer.

I have checked the path in the config file (configs/prompts/animation.yaml) and it is correct (pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse")
I have in the root a folder named: .pretrained_weights and in there a folder named: sd-vae-ft-mse and in there there are three files: config.json,  diffusion_pytorch_model.bin, diffusion_pytorch_model.safetensors.

But I'm getting that error.

Any ideas?

**Comment by lixunsong** [comment]
the folder name in the root may be `pretrained_weights/` instead of `.pretrained_weights`. Is it right?

**Comment by gunjahman** [comment]
Good idea. I tried it and now I get a different error:  raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by lixunsong** [comment]
This seems you don't install torch with a cuda version. You can first check whether the cuda is enabled by this:
```python
import torch
print(torch.cuda.is_available())
```
If output is False, you could reinstall torch.

**Comment by lixunsong** [comment]
We haven't encountered this issue in our environment, but I have two ideas:

1. Check if there are any errors when loading weights, for ReferenceUnet
2. Ensure that the image encoder is installed correctly according to the link we provided. We expect the hidden_dim of `enocder_hidden_state` to be 768, not 1024. I suspect this might be the reason.

**Comment by gunjahman** [comment]
Sorry, I'm a newbie. Where do I write: 
import torch
print(torch.cuda.is_available())

**Comment by nihilisticneuralnet** [comment]
you can create a new .py file within the folder and run it

**Comment by gunjahman** [comment]
Thank you. 
I did it, and you were right, I get FALSE

python check.py
False

What should I do?

**Comment by John-WL** [comment]
@gunjahman 
https://pytorch.org/
