### ISSUE TITLE
Getting model inference results is too slow

### ISSUE THREAD

**Issue by fsxbmb** [MooreThreads/Moore-AnimateAnyone#40]
Any tips for speeding up model inference? I used a 3090ti graphics card, but it took up to 10 minutes to generate a 4 second video.
![Snipaste_2024-01-16_16-47-55](https://github.com/MooreThreads/Moore-AnimateAnyone/assets/62832685/f71b8cd4-3e57-4bf0-b8f0-fa0cded26261)

**Comment by lixunsong** [comment]
We haven't specifically optimized for inference speed. Now a straightforward approach is to reduce the number of inference steps (perhaps 15~20 steps would be sufficient)

**Comment by fsxbmb** [comment]
> We haven't specifically optimized for inference speed. Now a straightforward approach is to reduce the number of inference steps (perhaps 15~20 steps would be sufficient)

Got it ！Wish you all the best.
