### ISSUE TITLE
I got decent results, but some of the samples were wrong, Could you provide us the training code?

### ISSUE THREAD

**Issue by AMujtaba57** [MooreThreads/Moore-AnimateAnyone#42]
Thank you for sharing the inference code and models @lixunsong ; the results are good, but further optimization is needed for stable outcomes. I would highly appreciate it if you could open source the training code as well.

https://github.com/MooreThreads/Moore-AnimateAnyone/assets/65533890/cc1514e1-3aab-485c-a3e6-82de6bd841fc

**Comment by lixunsong** [comment]
Hello @AMujtaba57 , the training code is available now.

**Comment by AMujtaba57** [comment]
alright and thanks @lixunsong
