### ISSUE TITLE
Some weights of the model checkpoint were not used when initializing "UNet2DConditionModel" ['conv_norm_out.weight, conv_norm_out.bias, conv_out.weight, conv_out.bias']

### ISSUE THREAD

**Issue by sdbds** [MooreThreads/Moore-AnimateAnyone#5]
When i try to load from safetensors i found some training weight problem.
Althrough it works in diffusers,but it had some hidden danger

**Comment by lixunsong** [comment]
Hello @sdbds , this is as expected, as we remove the top layers of ReferenceUnet: https://github.com/MooreThreads/Moore-AnimateAnyone/blob/7ccc423576badf64b4d04c2565f63da2e053c14f/src/models/unet_2d_condition.py#L648. These layers not contribute to the final output.

**Comment by sdbds** [comment]
> Hello @sdbds , this is as expected, as we remove the top layers of ReferenceUnet:
> 
> https://github.com/MooreThreads/Moore-AnimateAnyone/blob/7ccc423576badf64b4d04c2565f63da2e053c14f/src/models/unet_2d_condition.py#L648
> 
> . These layers not contribute to the final output.

I got it, thank you for replying！

**Comment by TZYSJTU** [comment]
> Hello @sdbds , this is as expected, as we remove the top layers of ReferenceUnet:
> 
> https://github.com/MooreThreads/Moore-AnimateAnyone/blob/7ccc423576badf64b4d04c2565f63da2e053c14f/src/models/unet_2d_condition.py#L648
> 
> . These layers not contribute to the final output.

But why are the top layers of the ReferenceUnet are removed?

**Comment by ja-nina** [comment]
@sdbds @TZYSJTU Any new information on why they are removed?

**Comment by huanngzh** [comment]
I think it is because the conv_out layer of reference unet does not participate in the calculation of loss, and an error will be reported during multi-card training.
