### ISSUE TITLE
different transforms in preprocess training data

### ISSUE THREAD

**Issue by chlinfeng1997** [MooreThreads/Moore-AnimateAnyone#53]
I noticed that different transformation operations are used for pose and image.
For pose:
self.cond_transform = transforms.Compose(
            [
                transforms.RandomResizedCrop(
                    self.img_size,
                    scale=self.img_scale,
                    ratio=self.img_ratio,
                    interpolation=transforms.InterpolationMode.BILINEAR,
                ),
                transforms.ToTensor(),
            ]
        )
For image:
self.transform = transforms.Compose(
            [
                transforms.RandomResizedCrop(
                    self.img_size,
                    scale=self.img_scale,
                    ratio=self.img_ratio,
                    interpolation=transforms.InterpolationMode.BILINEAR,
                ),
                transforms.ToTensor(),
                **transforms.Normalize([0.5], [0.5]),**
            ]
        )
Why does pose not require the final normalization step?

**Comment by lixunsong** [comment]
The pose image will not be processed by vae, so it's no need to normalize them into [-1, 1]. Please refer: https://github.com/huggingface/diffusers/blob/c9081a8abde4d9b660ff7af0ded43723c2ac9024/examples/controlnet/train_controlnet.py#L672
