### ISSUE TITLE
pose2img res is noise

### ISSUE THREAD

**Issue by renrenzsbbb** [MooreThreads/Moore-AnimateAnyone#59]
Thanks for your great work. I find that you add a pose2img pipeline. I sightly adjust the pose2vid.py to test. the adjustment is as follow: 
`                video = pipe(
                    ref_image_pil, # [512,512,1]
                    pose_list[0], # [768, 512]
                    width, # 576
                    height, # 768
                    # args.L, video length
                    args.steps,
                    args.cfg,
                    generator=generator,
                ).images`
However, the result is all noise. Can you give me some advices?

**Comment by lixunsong** [comment]
In the `pose2vid.py` script, motion module will be loaded into the denoising unet. This will lead the result noisy when only one image as input. You can refer the `log_validation` function in `train_stage_1.py` to ajust a pose2img generation script.
