### ISSUE TITLE
image normalization

### ISSUE THREAD

**Issue by jimmyl02** [MooreThreads/Moore-AnimateAnyone#63]
there was another issue discussing normalization but I was just curious when comparing the training and inference scripts.

in the training, there is a normalization of `Normalize([0.5], [0.5])` for the reference image but I don't see this in the inference pipeline; is there something that I'm missing about the pipeline? any advice would be super helpful, thanks!

**Comment by lixunsong** [comment]
The `VaeImageProcessor` in inference pipeline will do `Normalize([0.5], [0.5])` for the reference image
