### ISSUE TITLE
Is the backbone Denoising Unet need training？

### ISSUE THREAD

**Issue by TZYSJTU** [MooreThreads/Moore-AnimateAnyone#64]
Is the backbone Denoising Unet need to be finetuned? Or it is frozen as the SD 1.5 model?
In the paper, it says, "During this stage (second), we only train the temporal layer while fixing the weights of
the rest of the network.‘’
But I see your chechpoint containing the Denoising Unet?
So I got confused, please answer this question, thanks！

**Comment by lixunsong** [comment]
Denoising Unet is trained in the first stage and freezed in the second stage. Temporal layers are trained base on the stage-1 denoising unet.
