### ISSUE TITLE
training error in stage 1: denoising_unet.up_blocks.3.resnets.2.conv_shortcut.weight problem

### ISSUE THREAD

**Issue by TianQi-777** [MooreThreads/Moore-AnimateAnyone#66]
Thank you for sharing. I got this error when running (accelerate launch train_stage_1.py --config configs/train/stage1.yaml). Do you have any suggestions?

RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 1202 with name denoising_unet.up_blocks.3.resnets.2.conv_shortcut.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
Steps:   0%|                                                                            | 0/30000 [00:14<?, ?it/s]

**Comment by lixunsong** [comment]
Make sure `gradient_checkpointing` is disabled (`=False`). Now the code does not support it in the stage-1 training.

**Comment by TianQi-777** [comment]
OK, Thanks for your quick reply

**Comment by jsonkcli** [comment]
@TianQi-777 Hi Tian, can you help with my training?
