### ISSUE TITLE
max length 128

### ISSUE THREAD

**Issue by michaeltran33** [MooreThreads/Moore-AnimateAnyone#7]
Is there anyway to increase the length of the output video longer than 4sec?

**Comment by lixunsong** [comment]
Hello @michaeltran33 , what error message you get when exceeding length with 128? We do not limit the generation length, as long as the pose video has enough frames.

**Comment by inferno46n2** [comment]
I believe they are talking about the default gradio setup. It's capped at 128 frames.

I'm assuming editing the .py file for the gradio you can bypass?

**Comment by lixunsong** [comment]
> I believe they are talking about the default gradio setup. It's capped at 128 frames.
> 
> I'm assuming editing the .py file for the gradio you can bypass?

Yes , you are right. In the gradio setup, the max video length is 128. You can edit the code for a longer generation.

**Comment by G-force78** [comment]
> > I believe they are talking about the default gradio setup. It's capped at 128 frames.
> > I'm assuming editing the .py file for the gradio you can bypass?
> 
> Yes , you are right. In the gradio setup, the max video length is 128. You can edit the code for a longer generation.

Is it fixed at 128 with pose2vid too? I seem to get errors when I increase it past it

../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [498,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/Moore-AnimateAnyone/scripts/pose2vid.py", line 167, in <module>
    main()
  File "/content/Moore-AnimateAnyone/scripts/pose2vid.py", line 146, in main
    video = pipe(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Moore-AnimateAnyone/src/pipelines/pipeline_pose2vid_long.py", line 525, in __call__
    pred = self.denoising_unet(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Moore-AnimateAnyone/src/models/unet_3d.py", line 493, in forward
    sample, res_samples = downsample_block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Moore-AnimateAnyone/src/models/unet_3d_blocks.py", line 442, in forward
    hidden_states = attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Moore-AnimateAnyone/src/models/transformer_3d.py", line 140, in forward
    hidden_states = block(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/Moore-AnimateAnyone/src/models/mutual_self_attention.py", line 180, in hacked_basic_transformer_inner_forward
    norm_hidden_states[_uc_mask],
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by lixunsong** [comment]
If your pose video has less than 128 frames, the error will also be raised

**Comment by feiyangsuo** [comment]
> > > I believe they are talking about the default gradio setup. It's capped at 128 frames.
> > > I'm assuming editing the .py file for the gradio you can bypass?
> > 
> > 
> > Yes , you are right. In the gradio setup, the max video length is 128. You can edit the code for a longer generation.
> 
> Is it fixed at 128 with pose2vid too? I seem to get errors when I increase it past it Edit: I was setting it longer than the pose video. ../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [498,0,0], thread: [95,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
> 
> Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/content/Moore-AnimateAnyone/scripts/pose2vid.py", line 167, in main() File "/content/Moore-AnimateAnyone/scripts/pose2vid.py", line 146, in main video = pipe( File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/content/Moore-AnimateAnyone/src/pipelines/pipeline_pose2vid_long.py", line 525, in **call** pred = self.denoising_unet( File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/content/Moore-AnimateAnyone/src/models/unet_3d.py", line 493, in forward sample, res_samples = downsample_block( File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/content/Moore-AnimateAnyone/src/models/unet_3d_blocks.py", line 442, in forward hidden_states = attn( File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/content/Moore-AnimateAnyone/src/models/transformer_3d.py", line 140, in forward hidden_states = block( File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/content/Moore-AnimateAnyone/src/models/mutual_self_attention.py", line 180, in hacked_basic_transformer_inner_forward norm_hidden_states[_uc_mask], RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

replacing every `args.L` with `min(len(pose_images), args.L)` in pose2vid.py could fix this problem
