### ISSUE TITLE
Heavy artifacts appear when the video length is very small such as 5 and 10

### ISSUE THREAD

**Issue by TZYSJTU** [MooreThreads/Moore-AnimateAnyone#76]
I tried your pretrained weights, and I find when the video length is very short, such as  5 or 10 frames, the generated results will appear losts of artifacts, especially on the background. 

Besides, when I use long video, I can also ovserve some artifacts on the end or beginning of the video. 

I guess there may be some problem with the model to deal with the short videos and both ends of the video.

**Comment by TZYSJTU** [comment]
![9`4H8KDTO C 3%@925I8LZH](https://github.com/MooreThreads/Moore-AnimateAnyone/assets/47803475/a7870e8f-f6e2-4c61-a0c7-5e9f52d4e6de)

**Comment by TZYSJTU** [comment]
![Uploading image.png…]()

**Comment by TZYSJTU** [comment]
![%4K1V8RI3@~Z@N) ZXT`}GK](https://github.com/MooreThreads/Moore-AnimateAnyone/assets/47803475/67af9c4b-3775-43dc-9e98-b77dea1ccfa3)

**Comment by liutaocode** [comment]
I guess that is caused by the fixed length of motion module: 32. The model does not see any videos with less than 32 frames.
