### ISSUE TITLE
Question on datasets

### ISSUE THREAD

**Issue by shhh8444** [MooreThreads/Moore-AnimateAnyone#8]
Congratulations on achieving such amazing results!!! 
Both cartoons and real person can make smooth motion, so I have a question on which type of datasets did you use during training, like ubc datasets or dataset from tiktok?

**Comment by songtao-liu-mt** [comment]
We collect real-person videos from the web, and actually, cartoons are not included in our training data.

**Comment by lbwang2006** [comment]
> We collect real-person videos from the web, and actually, cartoons are not included in our training data.

how many videos can train this model well? 10k? 100k?

**Comment by lixunsong** [comment]
Right now it's about 10k videos
