### ISSUE TITLE
Training Process Error:  accelerator.backward(loss)

### ISSUE THREAD

**Issue by goshiaoki** [MooreThreads/Moore-AnimateAnyone#80]
When I run train_stage_1.py, "accelerator.backward(loss)" shows error like following. Could you help me to solve this error?

>Exception has occurred: RuntimeError
> Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

![Screenshot 2024-01-29 at 8 58 53 PM](https://github.com/MooreThreads/Moore-AnimateAnyone/assets/45219415/65deab60-7738-4022-a549-94de69158d9c)

I also tried adding "retain_graph=True" but it also doesn't work. 
![Screenshot 2024-01-29 at 8 58 14 PM](https://github.com/MooreThreads/Moore-AnimateAnyone/assets/45219415/18d15d76-ec1e-4317-841b-bf6c54c7f036)

**Comment by lixunsong** [comment]
Do you set `gradient_checkpointing=True` in traning?

**Comment by goshiaoki** [comment]
I set `gradient_checkpointing: True` in `stage1.yaml`. 
After changing to `gradient_checkpointing: False`, it can pass. 
Thank you!

**Comment by notorious-eric** [comment]
Hi the same error appears when I set gradient_accumulation_steps >1. I can set retain_graph=True but I do not know if this affects training.

**Comment by goshiaoki** [comment]
When I set the following, it works.

> train_bs: 2
> num_processes: 2

**Comment by houjie8888** [comment]
@goshiaoki hi, I meet the same error, where should "num_processes" be added, please

**Comment by bichunyang419** [comment]
可是gradient_checkpointing=True就不是梯度累计了呀，如何不加这个项跑通呢

**Comment by yuchenli-sony** [comment]
no iedae
